Feat: add modals
gustavosf2003/fresh-market pull request #18
Opened 2023-03-16 00:12 UTC by gustavosf2003

This PR adds modals by pressing the product card. Note that the description content has not yet been created in cms

2023-03-16 09:15 UTC, kkfuri requested changes

2023-03-16 09:15 UTC, kkfuri commented on src/components/CustomModal.tsx
> +          <Text className="text-xl ">{title}</Text>
space after class

2023-03-16 09:15 UTC, kkfuri commented on src/components/ProductModal.tsx
> +          <View className="mx-2 mt-6 ">
space after class

2023-03-16 09:15 UTC, kkfuri commented on src/components/ProductModal.tsx
> +    <CustomModal isOpen={isOpen} setIsOpen={setIsOpen} title={`#${product.id}`}>
No one cares about product id when purchasing, I think the title could be the name and having the id as a small SKU info on the product descript

2023-03-16 09:15 UTC, kkfuri commented on src/components/ProductModal.tsx
> +                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
Why use hard coded mock when you can mock the prop

2023-03-16 14:56 UTC, Pedrodev3 commented on src/components/ProductModal.tsx
> +    <CustomModal isOpen={isOpen} setIsOpen={setIsOpen} title={`#${product.id}`}>
I totally agree

2023-03-16 14:58 UTC, vitor-afonso approved these changes

2023-03-16 15:03 UTC, Pedrodev3 commented
Maybe if you change the title and subtitle to left and the picture to right using space-between, and after that use a minimal padding-x I believe the layout would improve and fit better in container

2023-03-16 23:15 UTC, gustavosf2003 commented on src/components/ProductModal.tsx
> +    <CustomModal isOpen={isOpen} setIsOpen={setIsOpen} title={`#${product.id}`}>
Make sense 🫡

2023-03-16 23:16 UTC, gustavosf2003 commented on src/components/ProductModal.tsx
> +                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
Changed to real value

2023-03-16 23:18 UTC, gustavosf2003 commented
> Maybe if you change the title and subtitle to left and the picture to right using space-between, and after that use a minimal padding-x I believe the layout would improve and fit better in container

I did it another way, the last design was terrible so I did some research and implemented it like this:
![image](https://user-images.githubusercontent.com/59636753/225773187-55d247dc-a504-4a92-8470-e6c23a41fac3.png)

2023-03-16 23:18 UTC, merged

2023-03-17 12:56 UTC, vitor-afonso commented
I like this one ❤️

2023-03-17 13:03 UTC, vitor-afonso commented on src/components/ProductCard.tsx
> +              {parseCurrency(
Wouldn't be better to have this logic in a function or variable and then just use it here to make readability easier?

2023-03-17 13:04 UTC, vitor-afonso commented on src/components/ProductCard.tsx
> +              )}
Wouldn't be better to have this logic in a function or variable and then just use it here to make readability easier?